/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimersRouteImport } from './routes/timers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotationsRouteImport } from './routes/rotations'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTimetableIdRouteImport } from './routes/t.$timetableId'

const TimersRoute = TimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationsRoute = RotationsRouteImport.update({
  id: '/rotations',
  path: '/rotations',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTimetableIdRoute = TTimetableIdRouteImport.update({
  id: '/t/$timetableId',
  path: '/t/$timetableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/display': typeof DisplayRoute
  '/rotations': typeof RotationsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/t/$timetableId': typeof TTimetableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/display': typeof DisplayRoute
  '/rotations': typeof RotationsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/t/$timetableId': typeof TTimetableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/display': typeof DisplayRoute
  '/rotations': typeof RotationsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/t/$timetableId': typeof TTimetableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/display'
    | '/rotations'
    | '/settings'
    | '/timers'
    | '/t/$timetableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/display'
    | '/rotations'
    | '/settings'
    | '/timers'
    | '/t/$timetableId'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/display'
    | '/rotations'
    | '/settings'
    | '/timers'
    | '/t/$timetableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  DisplayRoute: typeof DisplayRoute
  RotationsRoute: typeof RotationsRoute
  SettingsRoute: typeof SettingsRoute
  TimersRoute: typeof TimersRoute
  TTimetableIdRoute: typeof TTimetableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timers': {
      id: '/timers'
      path: '/timers'
      fullPath: '/timers'
      preLoaderRoute: typeof TimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotations': {
      id: '/rotations'
      path: '/rotations'
      fullPath: '/rotations'
      preLoaderRoute: typeof RotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$timetableId': {
      id: '/t/$timetableId'
      path: '/t/$timetableId'
      fullPath: '/t/$timetableId'
      preLoaderRoute: typeof TTimetableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  DisplayRoute: DisplayRoute,
  RotationsRoute: RotationsRoute,
  SettingsRoute: SettingsRoute,
  TimersRoute: TimersRoute,
  TTimetableIdRoute: TTimetableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
